[package]
name = "fastpbkdf2"
version = "0.1.0"
authors = ["jpixton@gmail.com"]
links = "fastpbkdf2"
build = "build.rs"

[lib]
name = "fastpbkdf2"
path = "src/lib.rs"

[dependencies]
libc = "0.1"

[build-dependencies]
gcc = "0.3"

